### ISSUE TITLE
Is the BitMagic One project dead?

### ISSUE THREAD

**Issue by julidau** [esden/bitmagic#1]
Hi,

while planning my logic analyzer project i came across this one. 

The Bitmagic One Schematic is essentially what i had in mind, but since the most recent change here is 3 years old, i wanted to ask if that project is dead or not. I would be interested in doing a layout for it if there is demand for such a thing. 

If it is dead i would also be interested in the reasons, since i haven't done any feasability studies yet :wink: 

PS: I hope this is the right place to ask this question, if not feel free to close this issue

**Comment by esden** [comment]
Bitmagic-One is not dead. It is postponed in favor of other projects like [Glasgow](https://www.crowdsupply.com/1bitsquared/glasgow) and [icebreaker-bitsy](https://github.com/icebreaker-fpga/icebreaker/tree/bitsy-v1.0a/hardware/bitsy-v1.0a) at the moment. But I do plan to work on bitmagic-pro and bitmagic-one some time this year. But the architecture will likely change on the one as I want to avoid using ftdi parts and there are good alternate approaches for this. Also bitmagic-one as it is at the moment does not differ much from [Glasgow](https://www.crowdsupply.com/1bitsquared/glasgow) so I am not sure there is a good reason to have both. But that is not decided yet.

**Comment by esden** [comment]
Also, this is the good place to ask in general. But if you want to discuss it any further I recommend you join our [Discord Srever](https://1bitsquared.com/pages/chat). We have a bitmagic specific channel on there and I will be posting there as soon as we start working on the other two models of it. I hope this answers all your questions. :) I am closing this issue.
